S2_G4_Fall2018/urls.py
from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "myapp"

urlpatterns = [
    # Index Page
    path('', views.home, name="home"),

    # Home Page
    path('about', views.about, name="about"),

    # Advertise Page
    path('advertise', views.advertise, name="advertise"),

    # Equipment Page
    path('equipment', views.equipment, name="equipment"),

    # SignIn Page
    path('signin', views.signin, name="signin"),

    # Contact Page
    path('contact', views.contact, name="contact"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from enum import Enum

# Create your models here.

## Proerty Category

class PropertyCategory(Enum):
    Single_House = "Single House"
    Attached_House = "Attached House"
    Town_House = "Town House"
    Apartment = "Apartment"
    Store = "Store"
    Farm = "Farm"
    Factory = "Factory"
    Mall = "Mall"
    Building = "Building"
    Other = "Other"


class Property_Category(models.Model):
    propertyCategory = models.CharField(
        max_length=5,
        choices=[(tag, tag.value) for tag in PropertyCategory]
    )

## Property Sector

class PropertySector(Enum):
    Private = "Private"
    Residential = "Residential"
    Commercial = "Commercial"
    Government = "Government"
    Rural = "Rural"
    Other = "Other"


class Property_Sector(models.Model):
    propertySector = models.CharField(
        max_length=5,
        choices=[(tag, tag.value) for tag in PropertySector]
    )

## Property_Facing

class PropertyFacing(Enum):
    North = "North"
    South = "South"
    East = "East"
    West = "West"
    Other = "Other"

class Property_Facing(models.Model):
    propertyFacing = models.CharField(
        max_length=5,
        choices=[(tag, tag.value) for tag in PropertyFacing]
    )

class Property(models.Model):
    propertyID = models.IntegerField(unique=True, primary_key=True, auto_created=True)
    propertyTitle = models.CharField(max_length=50)
    propertyCategory = models.ForeignKey(Property_Category, null=False)
    propertySector = models.ForeignKey(Property_Sector, null=False)
    propertyFacing = models.ForeignKey(Property_Facing, null=False)

myapp/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def advertise(request):
    return render(request, "advertise.html")

def equipment(request):
    return render(request, "sportequip.html")

def signin(request):
    return render(request, "signin.html")

def contact(request):
    return render(request, "contact.html")

myapp/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\about.css' %}">
{% endblock%}

{% block title %}About{% endblock %}

{% block content %}
<div class="container about">
    <h1>About Page</h1>
    <h2>Let us tell you something about us</h2>
    <div class="about-content text-center">
        <p id="about-para">
            This is a Real Estate system that maintains all the property information online. The system identifies and stores several types of property
            information. We provide a quick and easy way to search property information. Anyone can search for a specific property. Please create an account
            to upload a property for sale and rent, to register for a user account please visit the SignIn page.
        </p>
    </div>
</div>

{% endblock %}

myapp/templates/advertise.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\home.css' %}">
{% endblock%}

{% block title %}Advertise{% endblock %}

{% block content %}
<div>
    <h1>Welcome to advertise webpage</h1>
    <p>
        More details will come later
    </p>
    <h2>Under construction webpage</h2>
</div>

{% endblock %}

myapp/templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600" rel="stylesheet">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'myapp/css/base.css' %}">
    {% block css %}

    {% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
    <!--Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'myapp:home' %}"><img src="{% static 'myapp/images/logo.png' %}" width="50" height="50" class="d-inline-block align-top" alt=""></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <form class="form-inline mb-0" style="text-align: center">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:advertise' %}">Advertise Property</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:equipment' %}">Equipments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:signin' %}">SignIn/Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:contact' %}">Contact us</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="content text-center">
    {% block content %}
    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\home.css' %}">
{% endblock%}

{% block title %}Contact{% endblock %}

{% block content %}
<div>
    <h1>Welcome to Contact webpage</h1>
    <p>
        More details will come later
    </p>
    <h2>Under construction webpage</h2>
</div>

{% endblock %}

myapp/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\home.css' %}">
{% endblock%}

{% block title %}S2_G4_Fall2018{% endblock %}

{% block content %}
<div class="home">
    <h1>Welcome to our project webpage</h1>
    <p>
        More details will come later
    </p>
    <h2>Under construction webpage</h2>
</div>

{% endblock %}

myapp/templates/signin.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\home.css' %}">
{% endblock%}

{% block title %}Equipments{% endblock %}

{% block content %}
<div>
    <h1>Welcome to SignIn webpage</h1>
    <p>
        More details will come later
    </p>
    <h2>Under construction webpage</h2>
</div>

{% endblock %}

myapp/templates/sportequip.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css%}
<link rel="stylesheet" href="{% static 'myapp\css\equipment.css' %}">
{% endblock%}

{% block title %}S2_G4_Fall2018{% endblock %}

{% block content %}
<div class="container">
    <h1>Equipments</h1>
    <h2>List of equipments</h2>
    <div class="row text-center pt-5">
        <div class="col-md-3">
            <img src="{% static 'myapp/images/treadmill.jpg' %}" class="img-fluid" alt="Responsive image">
            <p class="img-text">
                Treadmill
            </p>
        </div>
        <div class="col-md-3">
            <img src="{% static 'myapp/images/elliptical.jpg' %}" class="img-fluid" alt="Responsive image">
            <p class = "img-text">
                Elliptical Machine
            </p>
        </div>
        <div class="col-md-3">
            <img src="{% static 'myapp/images/cycle.jpg' %}" class="img-fluid" alt="Responsive image">
            <p class="img-text">
                Exercie bike
            </p>
        </div>
        <div class="col-md-3">
            <img src="{% static 'myapp/images/dumbell.jpg' %}" class="img-fluid" alt="Responsive image">
            <p class="img-text">
                Dumbells
            </p>
        </div>
    </div>
</div>

{% endblock %}